### ISSUE TITLE
I CAN'T RUN BUSTER BECAUSE OF MISSING MODULE NAMED SERVER

### ISSUE THREAD

**Issue by algogarden** [paladini/ghost-on-github-pages#13]
Hi guys, Can someone help me? 
I got this error when run buster
`$ ./deploy.sh
[INFO] Deploying to your Github repository...
Traceback (most recent call last):
  File "c:\users\user\anaconda3\envs\py27\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\users\user\anaconda3\envs\py27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Users\user\Anaconda3\envs\py27\Scripts\buster.exe\__main__.py", line 5, in <module>
  File "c:\users\user\anaconda3\envs\py27\lib\site-packages\buster\buster.py", line 22, in <module>
    import http.server
ImportError: No module named server
On branch master
nothing to commit, working tree clean
fatal: I don't handle protocol '?`

But follow [https://github.com/waveform80/pistreaming/issues/14](url) , I need to use Python3 and It will not run buster anymore ( buster is only available with python2) . Any help would be greatly appreciated.

**Comment by paladini** [comment]
Thank you for reporting the buster / \http.server\ error on Windows.

**Classic v2.x** cannot fully fix this — buster + Python 2 on native Windows remains difficult. We documented workarounds in Classic [REQUIREMENTS](https://github.com/paladini/ghost-on-github-pages/blob/classic/v2/docs/legacy/REQUIREMENTS.md) (WSL recommended).

**Best fix:**
- **Version 3.0** (recommended): [https://github.com/paladini/ghost-on-github-pages/releases/latest](https://github.com/paladini/ghost-on-github-pages/releases/latest) — no Python 2 / buster; works well with WSL on Windows

**Classic maintenance:** [v2.0.2](https://github.com/paladini/ghost-on-github-pages/releases/tag/v2.0.2) improves other issues but not this Windows + Python 2 limitation.

Thanks for the report — it helped us document honest platform limits.
